apiVersion: v1
kind: Pod
metadata: 
  name: init-pod
spec:
  
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8011
      volumeMounts:
        - name: github-data
          mountPath: /usr/share/nginx/html
  initContainers:
    - name: my-init-container
      image: alpine
      command:
        - "wget"
        - "-O"
        - "/mnt/index.html"
        - "https://raw.githubusercontent.com/shiva2925/initContainer-new/main/index.html?raw=true"
      volumeMounts:
        - name: github-data
          mountPath: /mnt
  volumes:
    - name: github-data
      emptyDir: {}




    
