apiVersion: v1
kind: Pod
metadata:
  name: nginx-stadalone-pod
  labels:
    app: nginx
    env: dev
    version: v1
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8888
      volumeMounts:
        - name: nginx-pod-data
          mountPath: /var/www/html
  volumes:
    - name: nginx-pod-data
      emptyDir: {}

