apiVersion: v1
kind: Pod
metadata:
  name: nginx-stadalone-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-pod-data
          mountPath: /var/www/html
  volumes:
    - name: nginx-pod-data
      emptyDir: {}

