apiVersion: v1
kind: Pod
metadata:
  name: fieldref-env
spec:
  containers:
    - name: alpine-container
      image: alpine
      command: ["/bin/sh"]
      args: ["-c","while true; do echo $LIMIT_MEMORY >> /mnt/index.html;echo $LIMIT_CPU >> /mnt/index.html;  sleep 10;done"]
      resources:
        limits:
          cpu: "200m"
          memory: "250Mi"
        requests:
          cpu: "150m"
          memory: "200Mi"
      env:
        - name: LIMIT_MEMORY
          valueFrom:
            resourceFieldRef:
              containerName: alpine-container
              resource: limits.memory
            
        - name: LIMIT_CPU
          valueFrom:
            resourceFieldRef:
              containerName: alpine-container
              resource: limits.cpu
            
      volumeMounts:
        - name: downward-volume
          mountPath: /mnt
    - name: nginx-container
      image: nginx
      ports: 
        - containerPort: 80
          hostPort: 8090
      volumeMounts:
        - name: downward-volume
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: downward-volume
      emptyDir: {}
          
          

