apiVersion: v1
kind: Pod
metadata:
  name: fieldref-volume
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports: 
        - containerPort: 80
          hostPort: 8090
      volumeMounts:
        - name: downward-volume
          mountPath: /usr/share/nginx/html/ # if you mount your volume in the directory you check the data in browser
  volumes:
    - name: downward-volume
      downwardAPI:
        items:
          - path: index.html    # in index.html file, fieldPath: metadata.uid (pod id) will be added
            fieldRef: 
              fieldPath: metadata.uid
          

