apiVersion: v1
kind: Pod
metadata:
  name: fieldref-env
spec:
  containers:
    - name: alpine-container
      image: alpine
      command: ["/bin/sh"]
      args: ["-c","while true; do echo $POD_IP >> /mnt/index.html; echo $POD_ID >> /mnt/index.html; sleep 10;done"]
      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
      volumeMounts:
        - name: downward-volume
          mountPath: /mnt
    - name: nginx-container
      image: nginx
      ports: 
        - containerPort: 80
          hostPort: 8090
      volumeMounts:
        - name: downward-volume
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: downward-volume
      emptyDir: {}
          
          

