apiVersion: v1
kind: Pod
metadata: 
  name: empty-dir-ram-pod
spec:
  containers:
    - name: nginx-empty-conatiner
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: empty-volume-ram
          mountPath: /usr/share/nginx/html/ # /var/www/html/
  volumes:
    - name: empty-volume-ram
      emptyDir: 
        medium: Memory # it will create in memory (RAM).
        sizeLimit: 300Mi # give RAM size to utilize.