apiVersion: v1
kind: Pod
metadata: 
  name: empty-dir-ram-pod
spec:
  containers:
    - name: nginx-empty-conatiner
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8090
      volumeMounts:
        - name: hp-file-volume
          mountPath: /usr/share/nginx/html
     
  volumes:
    - name: hp-file-volume
      hostPath:
        path: /var/yamini
        type: DirectoryOrCreate 
    - name: hp-test-file
      hostPath:
        path: /var/yamini/home.html   
        type: FileOrCreate  # if type File--> will utizile the file but not create, if type: FileOrCreate--> it create if file doesnt exist
