apiVersion: v1
kind: Pod
metadata: 
  name: nfs-server-pod-2
spec:
  containers:
    - name: nginx-nfs-conatiner
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8090
      volumeMounts:
        - name: nfs-server
          mountPath: /usr/share/nginx/html
     
  volumes:
    - name: nfs-server
      nfs:
        server: 192.168.0.134 #other node server Ip address
        path: /nfs 