apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: my-sts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sts
      env: test
  template:
    metadata:
      labels:
        app: sts
        env: test
    spec:
      containers:
        - name: my-sts
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: sts-pvc
              mountPath: /usr/share/nginx/html/
  volumeClaimTemplates:
    - metadata:
        name: sts-pvc
      spec:
        storageClassName: sts-hostpath   #this parameter is used to bind the pvc
        accessModes:
          - ReadWriteOnce  
        resources:
          requests:
            storage: 1Gi       
