apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath
spec:
  storageClassName: hostpath   #this parameter is used to bind the pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi