apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replicas-pod
spec:
# replication info
  replicas: 3
  selector:
      app: nginx
      env: dev
      version: v1
# pod related infor written inside template   
  template:
    metadata: 
      labels:
        app: nginx
        env: dev
        version: v1
    spec: 
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-pod-data
              mountPath: /var/www/html
      volumes:
       - name: nginx-pod-data
         emptyDir: {}

        
      
   