apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector: #this selector key and values should match with pod labels
    app: nginx
    env: dev
    version: v1
  type: ClusterIP
  ports:
    - port: 8080       # port number for service
      targetPort: 80   # application port number
      protocol: TCP