apiVersion: v1
kind: Service
metadata:
  name: nginx-enternal-ip
spec:
  selector:
    app: nginx
    env: dev
    version: v1
  type: ClusterIP
  clusterIP: None
  
  ports:
    - name: http
      targetPort: 80
      port: 8080
      
  
 
