apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
spec:
  storageClassName: nfs   #this parameter is used to bind the pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi